#!/usr/bin/env bash



InstallDocker(){
  # Install docker
  sudo apt install apt-transport-https ca-certificates curl software-properties-common
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg --yes
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  
  sudo apt update
  apt-cache policy docker-ce
  sudo apt install docker-ce
  
  # Run docker without sudo. Trust me, you want this.
  sudo usermod -aG docker ${USER}
}

InstallNode(){
  # Install Node v18.17.1 and npm
  apt install nodejs
  apt install npm
  npm install -g n 
  n 18.17.1
}

InstallGuestAdditions(){
  # Virtual Box Guest Additions - to copy/paste and use shared folder between host and guest.
  apt install build-essential
  
  cd /media/rootuser/VBox_GAs_*
  ./VBoxLinuxAdditions.run
}

InstallVsCode(){
  # Install Visual Code
  sudo snap install --classic code # or code-insiders
}

InstallIfconfig(){
  # Install ifconfig
  apt install net-tools
}

SetupFirewallAllowSsh(){
  # Enable and set firewall to allow ssh
  ufw enable
  ufw allow ssh
}

SetGitCredentials(){
  touch /git_creds.sh
  chmod +x /git_creds.sh
  git config --global credential.helper "/bin/bash /git_creds.sh"
  
  echo "#!/bin/bash" >> /git_creds.sh
  echo "sleep 1" >> /git_creds.sh
  echo "echo username=$gitUsername" >> /git_creds.sh
  echo "echo password=$gitPat" >> /git_creds.sh
}

docker=Y
node=Y
nettools=Y
firewall=Y
vscode=Y
guestAdditions=Y
gitCredentials=Y


read -p "Install Docker? [Y/n] " -n 1 -r docker
echo
read -p "Install Node? [Y/n] " -n 1 -r node
echo
read -p "Install net-tools? [Y/n] " -n 1 -r nettools
echo
read -p "Setup Firewall (allow 22)? [Y/n] " -n 1 -r firewall
echo
read -p "Install VSCode? [Y/n] " -n 1 -r vscode
echo
read -p "Install Guest Additions? (Insert Guest Additions first) [Y/n] " -n 1 -r guestAdditions
echo
read -p "Permanently store git credentials? [Y/n] " -n 1 -r gitCredentials
echo
if ! [[ "$gitCredentials" =~ [Nn]$ ]]; 
then
  read -p "Username " -r gitUsername
  read -p "Personal Access Token " -r gitPat
  clear
fi


#yes | sudo apt update
#yes | sudo apt upgrade

if ! [[ "$docker" =~ [Nn]$ ]]; 
then
  yes | InstallDocker
fi

if ! [[ "$node" =~ [Nn]$ ]]; 
then
  yes | InstallNode
fi

if ! [[ "$nettools" =~ [Nn]$ ]]; 
then
  yes | InstallIfconfig
fi

if ! [[ "$firewall" =~ [Nn]$ ]]; 
then
  yes | SetupFirewallAllowSsh
fi

if ! [[ "$vscode" =~ [Nn]$ ]]; 
then
  yes | InstallVsCode
fi

if ! [[ "$guestAdditions" =~ [Nn]$ ]]; 
then
  InstallGuestAdditions # not using "yes" because that breaks it.
fi

if ! [[ "$gitCredentials" =~ [Nn]$ ]]; 
then
  SetGitCredentials
fi


echo "
Pwease westawt the system nyow                (づ ◕‿◕ )づ
It is vewy impowtant that you do that         ＼(º □ º l|l)/
i-it m-makes my head *cries* huwt othewwise   ~(>_<~)	                                                                                                                                                                                                                                                                                                                                                                                          
"

